pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - base=master
    actions:
      merge:
        method: merge